### ISSUE TITLE
Dataset template link is broken on Cards page

### ISSUE THREAD

**Issue by cleydyr** [liferay/lexicon-site#140]
At https://lexicondesign.io/docs/patterns/cards.html there's a link to dataset templates near the bottom of the page that goes to https://lexicondesign.io/docs/patterns/patterns/dataset_display.html. However, that page doesn't exist, and the user ends up with a 404 Not Found page. Maybe it was meant to be https://lexicondesign.io/docs/patterns/dataset_display.html.

**Comment by victorvalle** [comment]
Thanks @cleydyr ! it is solved in [PR141](https://github.com/liferay/lexicon-site/pull/141)
