### ISSUE TITLE
Inconsistence on Secondary Borderless Button 

### ISSUE THREAD

**Issue by dantasjadson** [liferay/lexicon-site#165]
Secondary borderless button has different variations (default, hover, active).
On the Analytics Cloud it has a variation, on the Figma's lib other and on the Lexicon's web site another. Also I checked on Clay site but there is no this type of button there.

Follow attached images from AC
![1 default](https://user-images.githubusercontent.com/1027401/48229545-296e8880-e387-11e8-87c5-bd6eb88fb7e0.png)
![2 hover](https://user-images.githubusercontent.com/1027401/48229546-2a071f00-e387-11e8-99bc-3efa978fb6e1.png)
![3 active](https://user-images.githubusercontent.com/1027401/48229547-2a071f00-e387-11e8-822e-1b1427648956.png)

**Comment by victorvalle** [comment]
Hi @dantasjadson 
So far we see in documentation that it is correct and also in Figma
![captura de pantalla 2018-11-12 a las 12 27 12](https://user-images.githubusercontent.com/21121115/48345100-5799e400-e677-11e8-80f8-c824e149b3bb.png)

I see it is not in Clay. You can request it there. But the action button should behave as such. To be clear, the Secondary and Secondary-borderless has the same style except for the border.

If in AC is wrong you should check with them if they made any variation to the css that forces it to be like that.
