### ISSUE TITLE
Use of english review

### ISSUE THREAD

**Issue by victorvalle** [liferay/lexicon-site#187]
Hi @mwilliams2014 ! Happy new year =)

Could you please review these two pages?
https://lexicondesign.io/docs/patterns/Forms/picker-color.html
https://lexicondesign.io/docs/patterns/Forms/picker-date-time.html

Thanks in advance for your time =)
Víctor

**Comment by mwilliams2014** [comment]
Reviewing now. Thanks!

**Comment by victorvalle** [comment]
Solved in https://github.com/liferay/lexicon-site/pull/189
