### ISSUE TITLE
Missed element on ClayCSS: M

### ISSUE THREAD

**Issue by dantasjadson** [liferay/lexicon-site#192]
@jbalsas 

Is the Multiple Select already available on ClayCSS?

*Selectors* component (https://lexiconupcoming.wedeploy.io/docs/patterns/Forms/selector.html) has _View in Clay_ label, it means _"The pattern was implemented"_  but while in LexiconIO we have both, Selector and Multiple Select, on ClasyCSS there is only Selector (https://clayui.com/docs/components/forms/selector.html)

Please, could you check it out? 
Thanks in advance.

cc: @victorvalle

**Comment by victorvalle** [comment]
This is an issue to open in Clay, not here. They are probably going to display it soon
