### ISSUE TITLE
Menu button not working on mobile

### ISSUE THREAD

**Issue by jonnilundy** [liferay/lexicon-site#9]
When inside of a documentation page on mobile (in my case, at lexicon-site.wedeploy.io/docs/alerts.html on Chrome on iOS) the topbar menu button is not responding. 

Seems to be working fine from the homepage.

**Comment by natecavanaugh** [comment]
Heya Jonni,
I can't seem to be able to reproduce this issue. Could you post some info on your system (and possibly clearing your browser's images and file cache)? You can clear the cache in Chrome in the top dropdown menu, Settings > Privacy > Clear Browsing Data.

I'm on an iPhone 6s, iOS 10.3.1, and Chrome 57.

**Comment by natecavanaugh** [comment]
Okay, after having talked with you about it, we both have come to the conclusion that it must be something related to Senna, as every fresh page reload works, but not when the page is loaded via ajax.
This also works on the desktop if you view the page in Chrome's devtools under the device mode.

I'll take a look at this one.

Thanks Jonni!

**Comment by jonnilundy** [comment]
Glad we could track down the issue. Thanks nate!
